name: fhir_time_machine
description: Converter extensions to translate between FHIR and Time Machine date/time types.
version: 1.0.2
repository: https://github.com/evoleen/fhir_time_machine

environment:
  sdk: ^3.7.0

# Add regular dependencies here.
dependencies:
  fhir: ^0.12.1
  time_machine2: ^0.12.1

dev_dependencies:
  lints: ^6.0.0
  test: ^1.26.3
