name: fhir_time_machine
description: Converter extensions to translate between FHIR and Time Machine date/time types.
version: 1.0.0
repository: https://github.com/evoleen/fhir_time_machine

environment:
  sdk: ^3.7.0

# Add regular dependencies here.
dependencies:
  fhir: ^0.12.0
  time_machine2: ^0.11.0

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
